#配置连接池
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/day5
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: a123

#配置JPA
  jpa:
    hibernate:
      ddl-auto: update    #配置更新表， 若表不存在就创建
    show-sql: true        #在控制台打印sql数据

#配置日志
logging:
  level:
    root: info