spring:
  datasource:
    url: jdbc:mysql://localhost:3306/day1
    username: root
    password: a123
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      #更新数据表，若没有则创建
      ddl-auto: update
    #控制台显示SQL
    show-sql: true