spring:
  datasource:
    username: root
    password: a123
    url: jdbc:mysql://localhost:3306/day3
    driver-class-name: com.mysql.jdbc.Driver
    #com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    # 以下配置若要使用，就要在DruidConfig类中配置生效！
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillist: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryt: SELECT 1 FROM DUAL
    tostWhileIdle: true
    testOnBorrowt: false
    testOnReturn: false
    poolPrcparedStatements: true
#    配置监控统计拦截的filters,去掉后监控界面sql无法统计，'wall '用于防火墙
    filters: stat ,wall,1og4j
    maxPoolPreparedStat cmentPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid. stat . mergeSq1=true;druid. stat . slowSqlMillis=500
