#配置连接池
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/day5
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: a123

#配置mybatis 配置文件
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

#配置日志
logging:
  level:
    root: info
