server:
  port: 33
spring:
  profiles:
    active: prod
---
server:
  port: 8084
spring:
  profiles: dev
---
server:
  port: 8085
spring:
  profiles: prod
---


#指定激活哪个配置文件， 这里激活dev _ application-dev.properties
#spring:
#  profiles:
#    active: dev


#为Person 设值
person:
  name: 张三
  age: 23
  sex: false
  date: 2018/1/12
  map: {k1: v1, k2: v2}
  list:
    - list1
    - list2
  dog:
    name: sb
    age: 1


